# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=1)),
                ('away', models.BooleanField(default=True)),
                ('awaytime', models.IntegerField(default=30)),
                ('willreturn', models.DateTimeField(auto_now_add=True)),
                ('name_es', models.CharField(max_length=64)),
                ('finished', models.BooleanField(default=False)),
                ('activepatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nextpatient', to='patient.patient')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('nextpatient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activepatient', to='patient.patient')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
