# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enthistory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTHistoryExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('duration', models.CharField(choices=[('n', 'none'), ('d', 'days'), ('w', 'weeks'), ('m', 'months'), ('i', 'intermittent'), ('p', 'permanent')], default='n', max_length=1)),
                ('side', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='b', max_length=1)),
                ('enthistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enthistory.enthistory')),
            ],
        ),
    ]
