# Generated by Django 5.2.15 on 2026-07-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=16)),
                ('user', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=256)),
                ('origin', models.CharField(max_length=128)),
                ('useragent', models.CharField(max_length=128)),
                ('auth', models.CharField(max_length=128)),
                ('auths', models.CharField(max_length=128)),
                ('body', models.CharField(max_length=1024)),
                ('files', models.CharField(max_length=1024)),
                ('content', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
