# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTSurgicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('tubes', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tubescomment', models.TextField(default='')),
                ('tplasty', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tplastycomment', models.TextField(default='')),
                ('eua', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('euacomment', models.TextField(default='')),
                ('fb', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('fbcomment', models.TextField(default='')),
                ('myringotomy', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('myringotomycomment', models.TextField(default='')),
                ('cerumen', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('cerumencomment', models.TextField(default='')),
                ('granuloma', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('granulomacomment', models.TextField(default='')),
                ('septorhinoplasty', models.BooleanField(default=False)),
                ('septorhinoplastycomment', models.TextField(default='')),
                ('scarrevision', models.BooleanField(default=False)),
                ('scarrevisioncomment', models.TextField(default='')),
                ('frenulectomy', models.BooleanField(default=False)),
                ('frenulectomycomment', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
