# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entdiagnosis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTDiagnosisExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=64)),
                ('value', models.TextField(default='')),
                ('entdiagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entdiagnosis.entdiagnosis')),
            ],
        ),
    ]
