#(C) Copyright Syd Logan 2016-2026
#(C) Copyright Thousand Smiles Foundation 2016-2026
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#
#You may obtain a copy of the License at
#http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

"""
Django settings for tscharts project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def print_directory_recursive_os_walk(start_path):
    """
    Recursively prints all directories and files starting from start_path
    using os.walk().
    """
    print(f"--- Directory tree starting from: {start_path} ---")
    for root, dirs, files in os.walk(start_path):
        # Calculate the current indentation level for a tree-like view
        level = root.replace(start_path, '').count(os.sep)
        indent = ' ' * 4 * level
        print(f'{indent}[{os.path.basename(root)}/]')

        subindent = ' ' * 4 * (level + 1)
        for f in files:
            print(f'{subindent}{f}')

BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = BASE_DIR / 'static'

import sys

# Define the path to your 'apps' directory
#APPS_DIR = BASE_DIR / 'app'
#
## Insert it into the Python system path
#sys.path.insert(0, str(APPS_DIR))
#
#APPS_DIR = BASE_DIR / 'app/tscharts/'
#
## Insert it into the Python system path
#sys.path.insert(0, str(APPS_DIR))

# Define the path to your 'apps' directory
APPS_DIR = BASE_DIR / 'tscharts'

# Insert it into the Python system path
sys.path.insert(0, str(APPS_DIR))

#print_directory_recursive_os_walk(str(BASE_DIR));

CHART_IMAGES_DIR = "/opt/thousandsmiles/images"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'rzu40a5v2wc#39&x-959)abrps2w+vb#kq8^m&s=-i%sl2ja0a'
ROOT_URLCONF = 'tscharts.urls'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent.parent


# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True

#ALLOWED_HOSTS = ["*"]

REGISTRATION_OPEN = True        # If True, users can register
ACCOUNT_ACTIVATION_DAYS = 7     # One-week activation window; you may, of course, use a different value.
REGISTRATION_AUTO_LOGIN = True  # If True, the user will be automatically logged in.
LOGIN_REDIRECT_URL = '/'  # The page you want users to arrive at after they successful log in
LOGIN_URL = '/accounts/login/'  # The page users are directed to if they are not logged in,
                                # and are trying to access pages requiring authentication
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    #'django_registration',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'registration',
    'rest_framework',
    'rest_framework.authtoken',
    'clinic.apps.ClinicConfig',
    'clinicstation.apps.ClinicstationConfig',
    'audiogram',
    'image',
    'covidvac',
    'dentalcdt',
    'dentalstate',
    'dentaltreatment',
    'entexam',
    'enthistory',
    'enthistoryextra',
    'enttreatment',
    'entdiagnosis',
    'entdiagnosisextra',
    'entsurgicalhistory',
    'medicalhistory',
    'mexicanstates',
    'patient',
    'pin',
    #'queue',  # legacy scheduling — no longer supported
    'register',
    'returntoclinic',
    'returntoclinicstation',
    'routingslip',
    'statechange',
    'station.apps.StationConfig',
    'tscharts',
    'medications',
    'surgerytype',
    'category',
    'surgeryhistory',
    'requestlog',
    'consent',
    'xray',
    'vaccine',
]

#MIDDLEWARE_CLASSES = [
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

#CSRF_COOKIE_SECURE = True

CSRF_TRUSTED_ORIGINS = [
    "https://localhost",
    "https://localhost:8000",
    "http://localhost",
    "http://localhost:8000",
    "http://127.0.0.1",
    # Add other trusted origins here if necessary
]

#CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    # Add your production domain names here later
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #'DIRS': [BASE_DIR / 'templates'],
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tscharts.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'tscharts',
#        'USER': 'root',
#        'PASSWORD': 'tscharts',
#        'HOST': '',
#        'PORT': '',
#        'OPTIONS': {
#           "init_command": "SET default_storage_engine=MyISAM",
#           'sql_mode': 'traditional',
#        }
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DATABASE_NAME', 'tscharts'),
        'USER': os.environ.get('DATABASE_USER', 'root'),
        'PASSWORD': os.environ.get('DATABASE_PASSWORD', 'tscharts'),
        'HOST': os.environ.get('DATABASE_HOST', 'db'), # Use the service name as the host
        'PORT': os.environ.get('DATABASE_PORT', '3306'),
        'OPTIONS': {
           "init_command": "SET default_storage_engine=MyISAM",
           'sql_mode': 'traditional',
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'  # set to local timezone

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),

    'DEFAULT_PERMISSION_CLASSES': [
       'rest_framework.permissions.IsAuthenticated',
       #'rest_framework.permissions.IsAdminUser'
    ]
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/tscharts.log',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers':['file'],
            'propagate': True,
            'level':'DEBUG',
        },
        'common': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
        'tscharts': {
            'handlers': ['file'],
            'propagate': True,
            'level': 'DEBUG',
        },
    }
}

# Match restored MySQL schema (int(11) AUTO_INCREMENT primary keys).
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
