# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
        ('returntoclinicstation', '0001_initial'),
        ('station', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('n', 'New Cleft'), ('d', 'Dental'), ('h', 'Hearing Aids'), ('e', 'Ears'), ('r', 'Returning Cleft'), ('o', 'Ortho'), ('t', 'Other')], default='t', max_length=1)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('statechangetime', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingSlipComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('routingslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routingslip.routingslip')),
            ],
        ),
        migrations.CreateModel(
            name='RoutingSlipEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('n', 'New'), ('s', 'Scheduled'), ('i', 'Checked In'), ('o', 'Checked Out'), ('r', 'Removed'), ('r', 'Deleted'), ('l', 'Return')], default='n', max_length=1)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('statechangetime', models.DateTimeField(auto_now=True)),
                ('returntoclinicstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='returntoclinicstation.returntoclinicstation')),
                ('routingslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routingslip.routingslip')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
