# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('time', models.DateTimeField(auto_now=True)),
                ('drainageSide', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='b', max_length=1)),
                ('drainageDuration', models.CharField(choices=[('n', 'none'), ('d', 'days'), ('w', 'weeks'), ('m', 'months'), ('i', 'intermittent'), ('p', 'permanent')], default='n', max_length=1)),
                ('hearingLossSide', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='b', max_length=1)),
                ('hearingLossDuration', models.CharField(choices=[('n', 'none'), ('d', 'days'), ('w', 'weeks'), ('m', 'months'), ('i', 'intermittent'), ('p', 'permanent')], default='n', max_length=1)),
                ('painSide', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='b', max_length=1)),
                ('painDuration', models.CharField(choices=[('n', 'none'), ('d', 'days'), ('w', 'weeks'), ('m', 'months'), ('i', 'intermittent'), ('p', 'permanent')], default='n', max_length=1)),
                ('comment', models.TextField(default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
