# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('cold_cough_fever', models.BooleanField(default=False)),
                ('hivaids', models.BooleanField(default=False)),
                ('anemia', models.BooleanField(default=False)),
                ('athsma', models.BooleanField(default=False)),
                ('cancer', models.BooleanField(default=False)),
                ('congenitalheartdefect', models.BooleanField(default=False)),
                ('congenitalheartdefect_workup', models.BooleanField(default=False)),
                ('congenitalheartdefect_planforcare', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('epilepsy', models.BooleanField(default=False)),
                ('bleeding_problems', models.BooleanField(default=False)),
                ('hepititis', models.BooleanField(default=False)),
                ('tuberculosis', models.BooleanField(default=False)),
                ('troublespeaking', models.BooleanField(default=False)),
                ('troublehearing', models.BooleanField(default=False)),
                ('troubleeating', models.BooleanField(default=False)),
                ('pregnancy_duration', models.IntegerField(default=9)),
                ('pregnancy_smoke', models.BooleanField(default=False)),
                ('birth_complications', models.BooleanField(default=False)),
                ('pregnancy_complications', models.BooleanField(default=False)),
                ('mother_alcohol', models.BooleanField(default=False)),
                ('relative_cleft', models.BooleanField(default=False)),
                ('parents_cleft', models.BooleanField(default=False)),
                ('siblings_cleft', models.BooleanField(default=False)),
                ('meds', models.TextField()),
                ('allergymeds', models.TextField()),
                ('first_crawl', models.IntegerField(default=7)),
                ('first_sit', models.IntegerField(default=8)),
                ('first_words', models.IntegerField(default=12)),
                ('first_walk', models.IntegerField(default=12)),
                ('birth_weight', models.IntegerField(default=0)),
                ('birth_weight_metric', models.BooleanField(default=True)),
                ('height', models.IntegerField(default=0)),
                ('height_metric', models.BooleanField(default=True)),
                ('weight', models.IntegerField(default=0)),
                ('weight_metric', models.BooleanField(default=True)),
                ('born_with_cleft_lip', models.BooleanField(default=False)),
                ('born_with_cleft_palate', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
