# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('clinicstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('state', models.CharField(choices=[('i', 'In'), ('o', 'Out')], default='o', max_length=1)),
                ('clinicstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicstation.ClinicStation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
            ],
        ),
    ]
