# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicstation', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('i', 'In'), ('o', 'Out')], default='o', max_length=1)),
                ('clinicstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicstation.clinicstation')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
