# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('dentalcdt', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('time', models.DateTimeField(auto_now=True)),
                ('tooth', models.IntegerField(default=0)),
                ('location', models.CharField(choices=[('t', 'top'), ('b', 'bottom')], default='t', max_length=1)),
                ('state', models.CharField(choices=[('m', 'missing'), ('n', 'none'), ('u', 'untreated'), ('t', 'treated'), ('o', 'other')], default='n', max_length=1)),
                ('surface', models.CharField(choices=[('n', 'none'), ('b', 'buccal'), ('u', 'lingual'), ('m', 'mesial'), ('c', 'occlusal'), ('a', 'labial'), ('i', 'incisal'), ('d', 'distal'), ('w', 'whole_mouth_or_visit'), ('o', 'other')], default='n', max_length=10)),
                ('comment', models.TextField(default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentalcdt.dentalcdt')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
