# Generated by Django 5.2.15 on 2026-07-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DentalCDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=12)),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
    ]
