# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('clinicstation', '0001_initial'),
        ('patient', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnToClinicStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('1', 'created'), ('2', 'scheduled_dest'), ('3', 'checked_out_dest'), ('4', 'scheduled_return')], default='1', max_length=1)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('statechangetime', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('requestingclinicstation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestingclinicstations', to='clinicstation.clinicstation')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='station.station')),
            ],
        ),
    ]
