# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-16 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('station', '0001_initial'),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagetype', models.CharField(choices=[('x', 'Xray'), ('h', 'Headshot'), ('s', 'Surgery')], max_length=1)),
                ('timestamp', models.DateField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.Clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.Station')),
            ],
        ),
    ]
