# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagetype', models.CharField(choices=[('x', 'Xray'), ('h', 'Headshot'), ('a', 'Audiogram'), ('s', 'Surgery')], max_length=1)),
                ('path', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
