# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('surgerytype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgeryyear', models.IntegerField(default=0)),
                ('surgerymonth', models.IntegerField(default=0)),
                ('surgerylocation', models.CharField(max_length=300)),
                ('anesthesia_problems', models.BooleanField(default=False)),
                ('bleeding_problems', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgerytype.surgerytype')),
            ],
        ),
    ]
