# Generated by Django 5.2.15 on 2026-07-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paternal_last', models.CharField(max_length=30)),
                ('maternal_last', models.CharField(max_length=30)),
                ('first', models.CharField(max_length=30)),
                ('middle', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=5)),
                ('prefix', models.CharField(max_length=5)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='f', max_length=1)),
                ('street1', models.CharField(max_length=64)),
                ('street2', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('AG', 'Aguascalientes'), ('BC', 'Baja California'), ('BS', 'Baja California Sur'), ('CH', 'Chihuahua'), ('CL', 'Colima'), ('CM', 'Campeche'), ('CO', 'Coahuila'), ('CS', 'Chiapas'), ('DF', 'Federal District'), ('DG', 'Durango'), ('GR', 'Guerrero'), ('GT', 'Guanajuato'), ('HG', 'Hidalgo'), ('JA', 'Jalisco'), ('ME', 'México State'), ('MI', 'Michoacán'), ('MO', 'Morelos'), ('NA', 'Nayarit'), ('NL', 'Nuevo León'), ('OA', 'Oaxaca'), ('PB', 'Puebla'), ('QE', 'Querétaro'), ('QR', 'Quintana Roo'), ('SI', 'Sinaloa'), ('SL', 'San Luis Potosí'), ('SO', 'Sonora'), ('TB', 'Tabasco'), ('TL', 'Tlaxcala'), ('TM', 'Tamaulipas'), ('VE', 'Veracruz'), ('YU', 'Yucatán'), ('ZA', 'Zacatecas')], default='BC', max_length=2)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('emergencyfullname', models.CharField(max_length=64)),
                ('emergencyphone', models.CharField(max_length=20)),
                ('emergencyemail', models.EmailField(max_length=254)),
                ('curp', models.CharField(default='', max_length=128)),
                ('oldid', models.IntegerField(default=-1)),
            ],
        ),
    ]
