# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('time', models.DateTimeField(auto_now=True)),
                ('normal', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('microtia', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('wax', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('drainage', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('externalOtitis', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('fb', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tubeRight', models.CharField(choices=[('p', 'in place'), ('e', 'extruding'), ('c', 'in canal'), ('n', 'none')], default='n', max_length=1)),
                ('tubeLeft', models.CharField(choices=[('p', 'in place'), ('e', 'extruding'), ('c', 'in canal'), ('n', 'none')], default='n', max_length=1)),
                ('tympanoRight', models.CharField(choices=[('a', 'anterior'), ('p', 'posterior'), ('2', '25 percent'), ('5', '50 percent'), ('7', '75 percent'), ('t', 'total'), ('n', 'none')], default='n', max_length=1)),
                ('tympanoLeft', models.CharField(choices=[('a', 'anterior'), ('p', 'posterior'), ('2', '25 percent'), ('5', '50 percent'), ('7', '75 percent'), ('t', 'total'), ('n', 'none')], default='n', max_length=1)),
                ('tmGranulations', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tmRetraction', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tmAtelectasis', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('perfRight', models.CharField(choices=[('a', 'anterior'), ('p', 'posterior'), ('m', 'marginal'), ('2', '25 percent'), ('5', '50 percent'), ('7', '75 percent'), ('t', 'total'), ('n', 'none')], default='n', max_length=1)),
                ('perfLeft', models.CharField(choices=[('a', 'anterior'), ('p', 'posterior'), ('m', 'marginal'), ('2', '25 percent'), ('5', '50 percent'), ('7', '75 percent'), ('t', 'total'), ('n', 'none')], default='n', max_length=1)),
                ('voiceTest', models.CharField(choices=[('n', 'normal'), ('a', 'abnormal'), ('o', 'none')], default='o', max_length=1)),
                ('forkAD', models.CharField(choices=[('a', 'a greater b'), ('b', 'b greater a'), ('e', 'a equal b'), ('n', 'none')], default='n', max_length=1)),
                ('forkAS', models.CharField(choices=[('a', 'a greater b'), ('b', 'b greater a'), ('e', 'a equal b'), ('n', 'none')], default='n', max_length=1)),
                ('bc', models.CharField(choices=[('a', 'ad lat ad'), ('b', 'ad lat as'), ('c', 'as lat ad'), ('d', 'as lat as'), ('n', 'none')], default='a', max_length=1)),
                ('fork', models.CharField(choices=[('2', '256'), ('5', '512'), ('n', 'none')], default='n', max_length=1)),
                ('comment', models.TextField(default='')),
                ('effusion', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('middle_ear_infection', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('cleft_lip', models.BooleanField(default=False)),
                ('cleft_palate', models.BooleanField(default=False)),
                ('repaired_lip', models.CharField(choices=[('a', 'na'), ('y', 'yes'), ('n', 'no')], default='a', max_length=1)),
                ('repaired_palate', models.CharField(choices=[('a', 'na'), ('y', 'yes'), ('n', 'no')], default='a', max_length=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
