# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('time', models.DateTimeField(auto_now=True)),
                ('exam', models.BooleanField(default=False)),
                ('examComment', models.TextField(default='')),
                ('prophy', models.BooleanField(default=False)),
                ('prophyComment', models.TextField(default='')),
                ('srpUR', models.BooleanField(default=False)),
                ('srpLR', models.BooleanField(default=False)),
                ('srpUL', models.BooleanField(default=False)),
                ('srpLL', models.BooleanField(default=False)),
                ('srpComment', models.TextField(default='')),
                ('xraysViewed', models.BooleanField(default=False)),
                ('xraysViewedComment', models.TextField(default='')),
                ('headNeckOralCancerExam', models.BooleanField(default=False)),
                ('headNeckOralCancerExamComment', models.TextField(default='')),
                ('oralHygieneInstruction', models.BooleanField(default=False)),
                ('oralHygieneInstructionComment', models.TextField(default='')),
                ('flourideTxVarnish', models.BooleanField(default=False)),
                ('flourideTxVarnishComment', models.TextField(default='')),
                ('nutritionalCounseling', models.BooleanField(default=False)),
                ('nutritionalCounselingComment', models.TextField(default='')),
                ('orthoEvaluation', models.BooleanField(default=False)),
                ('orthoEvaluationComment', models.TextField(default='')),
                ('orthoTx', models.BooleanField(default=False)),
                ('orthoTxComment', models.TextField(default='')),
                ('oralSurgeryEvaluation', models.BooleanField(default=False)),
                ('oralSurgeryEvaluationComment', models.TextField(default='')),
                ('oralSurgeryTx', models.BooleanField(default=False)),
                ('oralSurgeryTxComment', models.TextField(default='')),
                ('localAnestheticBenzocaine', models.BooleanField(default=False)),
                ('localAnestheticLidocaine', models.BooleanField(default=False)),
                ('localAnestheticSeptocaine', models.BooleanField(default=False)),
                ('localAnestheticOther', models.BooleanField(default=False)),
                ('localAnestheticNumberCarps', models.IntegerField(default=0)),
                ('localAnestheticComment', models.TextField(default='')),
                ('comment', models.TextField(default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
