# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('covid19', models.BooleanField(default=False)),
                ('covid19_type', models.CharField(max_length=64, null=True)),
                ('covid19_doses', models.IntegerField(default=0)),
                ('covid19_date', models.DateTimeField(null=True)),
                ('covid19_booster', models.BooleanField(default=False)),
                ('covid19_booster_date', models.DateTimeField(null=True)),
                ('dtap', models.BooleanField(default=False)),
                ('dtap_date', models.DateTimeField(null=True)),
                ('dt', models.BooleanField(default=False)),
                ('dt_date', models.DateTimeField(null=True)),
                ('hib', models.BooleanField(default=False)),
                ('hib_date', models.DateTimeField(null=True)),
                ('hepa', models.BooleanField(default=False)),
                ('hepa_date', models.DateTimeField(null=True)),
                ('hepb', models.BooleanField(default=False)),
                ('hepb_date', models.DateTimeField(null=True)),
                ('hpv', models.BooleanField(default=False)),
                ('hpv_date', models.DateTimeField(null=True)),
                ('iiv', models.BooleanField(default=False)),
                ('iiv_date', models.DateTimeField(null=True)),
                ('laiv4', models.BooleanField(default=False)),
                ('laiv4_date', models.DateTimeField(null=True)),
                ('mmr', models.BooleanField(default=False)),
                ('mmr_date', models.DateTimeField(null=True)),
                ('menacwy', models.BooleanField(default=False)),
                ('menacwy_date', models.DateTimeField(null=True)),
                ('menb', models.BooleanField(default=False)),
                ('menb_date', models.DateTimeField(null=True)),
                ('pcv13', models.BooleanField(default=False)),
                ('pcv13_date', models.DateTimeField(null=True)),
                ('ppsv23', models.BooleanField(default=False)),
                ('ppsv23_date', models.DateTimeField(null=True)),
                ('ipv', models.BooleanField(default=False)),
                ('ipv_date', models.DateTimeField(null=True)),
                ('rv', models.BooleanField(default=False)),
                ('rv_date', models.DateTimeField(null=True)),
                ('tap', models.BooleanField(default=False)),
                ('tap_date', models.DateTimeField(null=True)),
                ('td', models.BooleanField(default=False)),
                ('td_date', models.DateTimeField(null=True)),
                ('varicella', models.BooleanField(default=False)),
                ('varicella_date', models.DateTimeField(null=True)),
                ('dtap_hepb_ipv', models.BooleanField(default=False)),
                ('dtap_hepb_ipv_date', models.DateTimeField(null=True)),
                ('dtap_ipv_hib', models.BooleanField(default=False)),
                ('dtap_ipv_hib_date', models.DateTimeField(null=True)),
                ('dtap_ipv', models.BooleanField(default=False)),
                ('dtap_ipv_date', models.DateTimeField(null=True)),
                ('dtap_ipv_hib_hepb', models.BooleanField(default=False)),
                ('dtap_ipv_hib_hepb_date', models.DateTimeField(null=True)),
                ('mmvr', models.BooleanField(default=False)),
                ('mmvr_date', models.DateTimeField(null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
