# Generated by Django 5.2.15 on 2026-07-05 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENTDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=64)),
                ('comment', models.TextField(default='')),
                ('time', models.DateTimeField(auto_now=True)),
                ('hlConductive', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('hl', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('hlMixed', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('hlSensory', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('externalCerumenImpaction', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('externalEarCanalFB', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('externalMicrotia', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tympanicAtelectasis', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tympanicGranuloma', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tympanicMonomer', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tympanicTube', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('tympanicPerf', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('middleEarCholesteatoma', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('middleEarEustTubeDysTMRetraction', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('middleEarOtitisMedia', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('middleEarSerousOtitisMedia', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('oralAnkyloglossia', models.BooleanField(default=False)),
                ('oralTonsilEnlarge', models.BooleanField(default=False)),
                ('oralCleftLipRepairDeformity', models.BooleanField(default=False)),
                ('oralCleftLipUnilateral', models.BooleanField(default=False)),
                ('oralCleftLipBilateral', models.BooleanField(default=False)),
                ('oralCleftLipUnrepaired', models.BooleanField(default=False)),
                ('oralCleftLipRepaired', models.BooleanField(default=False)),
                ('oralCleftPalateUnilateral', models.BooleanField(default=False)),
                ('oralCleftPalateBilateral', models.BooleanField(default=False)),
                ('oralCleftPalateUnrepaired', models.BooleanField(default=False)),
                ('oralCleftPalateRepaired', models.BooleanField(default=False)),
                ('oralSpeechProblem', models.BooleanField(default=False)),
                ('noseDeviatedSeptum', models.BooleanField(default=False)),
                ('noseTurbinateHypertrophy', models.BooleanField(default=False)),
                ('noseDeformitySecondaryToCleftPalate', models.BooleanField(default=False)),
                ('syndromeHemifacialMicrosomia', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('syndromePierreRobin', models.CharField(choices=[('l', 'left'), ('r', 'right'), ('b', 'both'), ('n', 'none')], default='n', max_length=1)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
